spring:
  datasource:
      druid:
        username: root
        password: Zw726515
        jdbcUrl: jdbc:mysql://localhost:3306/tuling-ms-alibaba?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        filters: stat,wall #\u914D\u7F6E\u8FC7\u6EE4\u5668
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

        #cluster-name: NJ-CLUSTER
        #metadata:
          #current-version: V1

        #namespace: bc7613d2-2e22-4292-a748-48b78170f14c  #指定namespace的id
  application:
    name: order-center

#自定义Ribbon的细粒度配置


#ribbon:
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  #eager-load:
    #enabled: true
#product-center:
  #ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #eager-load:
      #enabled: true
server:
  port: 8080



